[build]
pkgs = ["python311"]
builder = "nixpacks"
buildCommand = "pip install -r requirements/prod.txt && cd web && python manage.py collectstatic --noinput"

[deploy]
startCommand = "cd web && python manage.py runserver 0.0.0.0:8000"
restartPolicyType = "ON_FAILURE"